name: "Challenge 3"

on: [push]
env:
    ARTIFACT_NAME: some_artifact

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout the repo
          uses: actions/checkout@v2
        - name: Test
          run: python .github/scripts/hello.py
    build:
        runs-on: ubuntu-latest
        needs: [test]
        steps:
        - name: Checkout the repo
          uses: actions/checkout@v2
        - name: Create an artifact
          uses: actions/upload-artifact@v4
          with:
            name: ${{env.ARTIFACT_NAME}}
            path: .


