name: "Use MVP custom action"

on: push

jobs:
    run_custom_action:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v2
         - uses: bugagashen6ka/custom-mvp-action@v1.0.0